export var countries = [
    {label: 'Абхазия', value: 'AB'},
    {label: 'Австралия', value: 'AU'},
    {label: 'Австрия', value: 'AT'},
    {label: 'Азербайджан', value: 'AZ'},
    {label: 'Албания', value: 'AL'},
    {label: 'Алжир', value: 'DZ'},
    {label: 'Ангола', value: 'AO'},
    {label: 'Андорра', value: 'AD'},
    {label: 'Антигуа и Барбуда', value: 'AG'},
    {label: 'Аргентина', value: 'AR'},
    {label: 'Армения', value: 'AM'},
    {label: 'Афганистан', value: 'AF'},
    {label: 'Багамские Острова', value: 'BS'},
    {label: 'Бангладеш', value: 'BD'},
    {label: 'Барбадос', value: 'BB'},
    {label: 'Бахрейн', value: 'BH'},
    {label: 'Белиз', value: 'BZ'},
    {label: 'Беларусь', value: 'BY'},
    {label: 'Бельгия', value: 'BE'},
    {label: 'Бенин', value: 'BJ'},
    {label: 'Болгария', value: 'BG'},
    {label: 'Боливия', value: 'BO'},
    {label: 'Босния и Герцеговина', value: 'BA'},
    {label: 'Ботсвана', value: 'BW'},
    {label: 'Бразилия', value: 'BR'},
    {label: 'Бруней', value: 'BN'},
    {label: 'Буркина-Фасо', value: 'BF'},
    {label: 'Бурунди', value: 'BI'},
    {label: 'Бутан', value: 'BT'},
    {label: 'Вануату', value: 'VU'},
    {label: 'Ватикан', value: 'VA'},
    {label: 'Великобритания', value: 'GB'},
    {label: 'Венгрия', value: 'HU'},
    {label: 'Венесуэла', value: 'VE'},
    {label: 'Восточный Тимор', value: 'TL'},
    {label: 'Вьетнам', value: 'VN'},
    {label: 'Габон', value: 'GA'},
    {label: 'Гаити', value: 'HT'},
    {label: 'Гайана', value: 'GY'},
    {label: 'Гамбия', value: 'GM'},
    {label: 'Гана', value: 'GH'},
    {label: 'Гватемала', value: 'GT'},
    {label: 'Гвинея', value: 'GN'},
    {label: 'Гвинея-Бисау', value: 'GW'},
    {label: 'Германия', value: 'DE'},
    {label: 'Гондурас', value: 'HN'},
    {label: 'Государство Палестина', value: 'PS'},
    {label: 'Гренада', value: 'GD'},
    {label: 'Греция', value: 'GR'},
    {label: 'Грузия', value: 'GE'},
    {label: 'Дания', value: 'DK'},
    {label: 'Джибути', value: 'DJ'},
    {label: 'Доминика', value: 'DM'},
    {label: 'Доминиканская Республика', value: 'DO'},
    {label: 'ДР Конго', value: 'CD'},
    {label: 'Египет', value: 'EG'},
    {label: 'Замбия', value: 'ZM'},
    {label: 'Зимбабве', value: 'ZW'},
    {label: 'Израиль', value: 'IL'},
    {label: 'Индия', value: 'IN'},
    {label: 'Индонезия', value: 'ID'},
    {label: 'Иордания', value: 'JO'},
    {label: 'Ирак', value: 'IQ'},
    {label: 'Иран', value: 'IR'},
    {label: 'Ирландия', value: 'IE'},
    {label: 'Исландия', value: 'IS'},
    {label: 'Испания', value: 'ES'},
    {label: 'Италия', value: 'IT'},
    {label: 'Йемен', value: 'YE'},
    {label: 'Кабо-Верде', value: 'CV'},
    {label: 'Казахстан', value: 'KZ'},
    {label: 'Камбоджа', value: 'KH'},
    {label: 'Камерун', value: 'CM'},
    {label: 'Канада', value: 'CA'},
    {label: 'Катар', value: 'QA'},
    {label: 'Кения', value: 'KE'},
    {label: 'Кипр', value: 'CY'},
    {label: 'Киргизия', value: 'KG'},
    {label: 'Кирибати', value: 'KI'},
    {label: 'Китай', value: 'CN'},
    {label: 'КНДР', value: 'KP'},
    {label: 'Колумбия', value: 'CO'},
    {label: 'Коморские Острова', value: 'KM'},
    {label: 'Коста-Рика', value: 'CR'},
    {label: 'Кот-д\'Ивуар', value: 'CI'},
    {label: 'Куба', value: 'CU'},
    {label: 'Кувейт', value: 'KW'},
    {label: 'Лаос', value: 'LA'},
    {label: 'Латвия', value: 'LV'},
    {label: 'Лесото', value: 'LS'},
    {label: 'Либерия', value: 'LR'},
    {label: 'Ливан', value: 'LB'},
    {label: 'Ливия', value: 'LY'},
    {label: 'Литва', value: 'LT'},
    {label: 'Лихтенштейн', value: 'LI'},
    {label: 'Люксембург', value: 'LU'},
    {label: 'Маврикий', value: 'MU'},
    {label: 'Мавритания', value: 'MR'},
    {label: 'Мадагаскар', value: 'MG'},
    {label: 'Малави', value: 'MW'},
    {label: 'Малайзия', value: 'MY'},
    {label: 'Мали', value: 'ML'},
    {label: 'Мальдивские Острова', value: 'MV'},
    {label: 'Мальта', value: 'MT'},
    {label: 'Марокко', value: 'MA'},
    {label: 'Маршалловы Острова', value: 'MH'},
    {label: 'Мексика', value: 'MX'},
    {label: 'Мозамбик', value: 'MZ'},
    {label: 'Молдавия', value: 'MD'},
    {label: 'Монако', value: 'MC'},
    {label: 'Монголия', value: 'MN'},
    {label: 'Мьянма', value: 'MM'},
    {label: 'Намибия', value: 'NA'},
    {label: 'Науру', value: 'NR'},
    {label: 'Непал', value: 'NP'},
    {label: 'Нигер', value: 'NE'},
    {label: 'Нигерия', value: 'NG'},
    {label: 'Нидерланды', value: 'NL'},
    {label: 'Никарагуа', value: 'NI'},
    {label: 'Новая Зеландия', value: 'NZ'},
    {label: 'Норвегия', value: 'NO'},
    {label: 'ОАЭ', value: 'AE'},
    {label: 'Оман', value: 'OM'},
    {label: 'Пакистан', value: 'PK'},
    {label: 'Палау', value: 'PW'},
    {label: 'Панама', value: 'PA'},
    {label: 'Папуа - Новая Гвинея', value: 'PG'},
    {label: 'Парагвай', value: 'PY'},
    {label: 'Перу', value: 'PE'},
    {label: 'Польша', value: 'PL'},
    {label: 'Португалия', value: 'PT'},
    {label: 'Республика Конго', value: 'CG'},
    {label: 'Республика Корея', value: 'KR'},
    {label: 'Россия', value: 'RU'},
    {label: 'Руанда', value: 'RW'},
    {label: 'Румыния', value: 'RO'},
    {label: 'Сальвадор', value: 'SV'},
    {label: 'Самоа', value: 'WS'},
    {label: 'Сан-Марино', value: 'SM'},
    {label: 'Сан-Томе и Принсипи', value: 'ST'},
    {label: 'Саудовская Аравия', value: 'SA'},
    {label: 'Северная Македония', value: 'MK'},
    {label: 'Сейшельские Острова', value: 'SC'},
    {label: 'Сенегал', value: 'SN'},
    {label: 'Сент-Винсент и Гренадины', value: 'VC'},
    {label: 'Сент-Китс и Невис', value: 'KN'},
    {label: 'Сент-Люсия', value: 'LC'},
    {label: 'Сербия', value: 'RS'},
    {label: 'Сингапур', value: 'SG'},
    {label: 'Сирия', value: 'SY'},
    {label: 'Словакия', value: 'SK'},
    {label: 'Словения', value: 'SI'},
    {label: 'Соломоновы Острова', value: 'SB'},
    {label: 'Сомали', value: 'SO'},
    {label: 'Судан', value: 'SD'},
    {label: 'Суринам', value: 'SR'},
    {label: 'США', value: 'US'},
    {label: 'Сьерра-Леоне', value: 'SL'},
    {label: 'Таджикистан', value: 'TJ'},
    {label: 'Таиланд', value: 'TH'},
    {label: 'Танзания', value: 'TZ'},
    {label: 'Того', value: 'TG'},
    {label: 'Тонга', value: 'TO'},
    {label: 'Тринидад и Тобаго', value: 'TT'},
    {label: 'Тувалу', value: 'TV'},
    {label: 'Тунис', value: 'TN'},
    {label: 'Туркмения', value: 'TM'},
    {label: 'Турция', value: 'TR'},
    {label: 'Уганда', value: 'UG'},
    {label: 'Узбекистан', value: 'UZ'},
    {label: 'Украина', value: 'UA'},
    {label: 'Уругвай', value: 'UY'},
    {label: 'Федеративные Штаты Микронезии', value: 'FM'},
    {label: 'Фиджи', value: 'FJ'},
    {label: 'Филиппины', value: 'PH'},
    {label: 'Финляндия', value: 'FI'},
    {label: 'Франция', value: 'FR'},
    {label: 'Хорватия', value: 'HR'},
    {label: 'ЦАР', value: 'CF'},
    {label: 'Чад', value: 'TD'},
    {label: 'Черногория', value: 'ME'},
    {label: 'Чехия', value: 'CZ'},
    {label: 'Чили', value: 'CL'},
    {label: 'Швейцария', value: 'CH'},
    {label: 'Швеция', value: 'SE'},
    {label: 'Шри-Ланка', value: 'LK'},
    {label: 'Эквадор', value: 'EC'},
    {label: 'Экваториальная Гвинея', value: 'GQ'},
    {label: 'Эритрея', value: 'ER'},
    {label: 'Эсватини', value: 'SZ'},
    {label: 'Эстония', value: 'EE'},
    {label: 'Эфиопия', value: 'ET'},
    {label: 'ЮАР', value: 'ZA'},
    {label: 'Южная Осетия', value: 'OS'},
    {label: 'Южный Судан', value: 'SS'},
    {label: 'Ямайка', value: 'JM'},
    {label: 'Япония', value: 'JP'}];

export function getCountry(code) {
    return countries.find(element => element.value === code).label;
}